### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by iddm** [dust-engine/NRD#1]
Hi. I am writing a Vulkan path-tracing game for fun. If this crate works well, I'd like to request co-maintainership access to be able to update it right here and not in a fork, if you don't mind. There are already way too many works for every single little crate in Rust, I think we should organise into a community more often than never. What do you think?

**Comment by vityafx** [comment]
The crate doesn't seem to build when used from the crates.io:

```
error: failed to run custom build command for `nrd-sys v0.1.0`

Caused by:
  process didn't exit successfully: `/home/user/workspace/engine-rs/target/debug/build/nrd-sys-e235fe8dddfc9b8a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nrd-sys-0.1.0/build.rs:35:14:
  Download file error: CommandFailed { status: ExitStatus(unix_wait_status(2048)), stdout: , stderr:  }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
